config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]

    collection do
      
      get :feeds

      get :ranking

    end

    member do

      get :dashboard
    
      post :favorite
      post :unfavorite

      post :like
      post :unlike

    end

  end

  resources :users, only: [:show, :edit, :update]

  resources :categories, only: :show
  root "restaurants#index"

  namespace :admin do
    resources :restaurants
    resources :categories
    root "restaurants#index"
  end

end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :name
  has_many :restaurants, dependent: :restrict_with_error
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
    
    before_action :authenticate_admin
    before_action :set_category, only:[:update, :destroy]

    def index
      @categories = Category.all

      if params[:id]
        set_category
      else
        @category = Category.new
      end
    end

    def create
      @category = Category.new(category_params)

      if @category.save
       flash[:notice] = "category was successfully created"
       redirect_to admin_categories_path

     else
      @categories = Category.all
      render :index
     end
    end

    def update

    if @category.update(category_params)
     redirect_to admin_categories_path
     flash[:notice] = "category was successfully updated"

    else
      @categories = Category.all
      render :index
     end
    end

    def destroy
      @category.destroy
      flash[:alert] = "category was successfully deleted"
      redirect_to admin_categories_path
    end
 
private

  def category_params
   params.require(:category).permit(:name)
  end

  def set_category
    @category = Category.find(params[:id])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    @categories = Category.all
    @category = Category.find(params[:id])
    @restaurants = @category.restaurants.page(params[:page]).per(9)
  end

  def destroy
    @category.destroy

    if @category.errors
      flash[:alert] = @category.errors.full_message.to_sentence
    else
      flash[:notice] = "category was sucessfully deleted"
    end

      edirect_to admin_categories_path
    end

end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/index.html.erb
<div class="container">

  <h1>餐廳分類總表</h1>

  <div class="row">

    <div class="col-md-12">

      <table class="table table-striped table-bordered">
         <div>
            <%= link_to 'Restaurant', admin_restaurants_path %> |
            <%= link_to 'Categories', admin_categories_path %>
        </div>

        <div class="form-inline" >
         <%= form_for [:admin, @category] do |f| %>
        <div class="form-group">
          <%= f.text_field :name, placeholder: "Category Name",  class: "form-control" %>
        </div>
           <%= f.submit class: "btn btn-primary" %>
          <% end %>
          <% if @category.errors.any? %>
           <%= @category.errors.full_messages.to_sentence %>
          <% end %>
        </div>

        

        <thead>
          <tr>
            <th>#</th>
            <th>Category Name</th>
            <th>#</th>
          </tr>
        </thead>
        <tbody>
          <% @categories.each do |category| %>
          <tr>
            <th scope="row"><%= category.id %></th>
            <td><%= category.name %></td>
            <td>
               <%= link_to 'Edit', admin_categories_path(id: category.id) %>
               <%= link_to 'Delete', admin_category_path(category), method: :delete, data: { confirm: "Are you sure?"} %>
             </td>

          </tr>
          <% end %>
        </tbody>
      </table>

    </div>

  </div>
</div>